version: '3.9'

services:
  # MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes: 
      - mongo_db:/data/db

  # Node API service
  api:
    build: .
    ports:
      - 7000:3030   #外部からlocalhost:7000を通じて、コンテナ内の3030にアクセスできる。
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 3030
      MONGODB_URI: mongodb+srv://app:passw0rd@cluster0.l6nul.mongodb.net/creation?retryWrites=true&w=majority&appName=Cluster0
      DB_NAME: creation
      NAME: TrulyMittal
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}